export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_WISHLIST_PRODUCTS = "GET_WISHLIST_PRODUCTS"
export const GET_SORTED_PRODUCT = "GET_SORTED_PRODUCT"
export const GET_HOVER_PRODUCT = "GET_HOVER_PRODUCT"
export const GET_CART_PRODUCT = "GET_CART_PRODUCT"
export const ADD_TO_CART = "ADD_TO_CART"
export const GET_SELECTED_ITEM_COUNT = "GET_SELECTED_ITEM_COUNT"
export const MOVE_TO_CART = "MOVE_TO_CART"
export const GET_CART_ITEMS = "GET_CART_ITEMS"
export const GET_CARTITEMS_COUNT="GET_CARTITEMS_COUNT"


